# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-30 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='uid',
            field=models.CharField(default=uuid.UUID('ba9bdf56-6b34-4930-86fa-36e426f6cb6a'), max_length=40),
        ),
    ]
