# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-30 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='uid',
            field=models.CharField(default=uuid.UUID('ccc8e9a0-005e-40d4-9be6-a22084db0fe5'), max_length=40),
        ),
    ]
