# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-02 05:51
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190530_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='uid',
            field=models.CharField(default=uuid.UUID('a63f6b66-6280-4cf2-80b8-f8c2131c21ed'), max_length=40),
        ),
    ]
