# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-02 11:18
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190530_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='uid',
            field=models.CharField(default=uuid.UUID('16fcdedc-a0ed-459c-9700-fde5ddc15bf7'), max_length=40),
        ),
    ]
