# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-02 18:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190602_1118'),
        ('accounts', '0003_auto_20190602_0551'),
    ]

    operations = [
    ]
